services:
  document-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-service
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DOCUMENT_OUTPUT_PATH: /app/generated-documents
    volumes:
      - generated_documents:/app/generated-documents
    networks:
      - kafka

networks:
  # External network created by the agro_trade compose project (shared Kafka).
  kafka:
    external: true
    name: agro_trade_default

volumes:
  generated_documents: